# Generated by Django 4.1.7 on 2023-10-07 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryBloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_num', models.IntegerField()),
                ('data', models.CharField(default='--', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Local', 'Local'), ('Home', 'Home'), ('Remote', 'Remote')], default='Home', max_length=30)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MessageSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_message', models.CharField(choices=[('7', 'Data Write-Back'), ('2', 'Write Miss'), ('1', 'Read Miss'), ('5', 'Fetch'), ('3', 'Data Value Reply'), ('6', 'Fetch/Invalidate'), ('4', 'Invalidate')], max_length=30)),
                ('content_msg', models.CharField(max_length=20)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest', to='protocole.node')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src', to='protocole.node')),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('1', 'Uncached'), ('2', 'Shared'), ('3', 'Modified'), ('4', 'Invalid')], default='1', max_length=30)),
                ('owner_bits', models.CharField(max_length=5)),
                ('bloc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='protocole.memorybloc')),
            ],
        ),
        migrations.CreateModel(
            name='CacheNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_cache', models.CharField(choices=[('1', 'Uncached'), ('2', 'Shared'), ('3', 'Modified'), ('4', 'Invalid')], max_length=20)),
                ('bloc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocole.memorybloc')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocole.node')),
            ],
        ),
    ]
