# Generated by Django 4.1.7 on 2023-10-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocole', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesimulation',
            name='destination',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='messagesimulation',
            name='source',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='messagesimulation',
            name='type_message',
            field=models.CharField(choices=[('1', 'Read Miss'), ('2', 'Write Miss'), ('3', 'Data Value Reply'), ('4', 'Invalidate'), ('5', 'Fetch'), ('6', 'Fetch/Invalidate'), ('7', 'Data Write-Back')], max_length=30),
        ),
    ]
